/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright 2026 Diametrical Ltd. */
/*
 * FuaranCore — the C-ABI header shim for the Fuaran UI wire-format Rust
 * reference core. This target exposes the hand-written `fuaran.h` surface to
 * Swift as an importable module; the concrete symbols are resolved at link time
 * from the Rust reference core's native staticlib. (An xcframework binary target
 * was described here and never existed — see README "Consuming a live session".)
 * This translation unit exists only so the target has a source file; it carries no
 * logic.
 *
 * `include/fuaran.h` is a GENERATED byte-copy of the reference core's header,
 * byte-compared by `run.ps1` and by the CI job that checks out both repositories.
 * Do not hand-edit it: regenerate it from the reference and read the diff.
 */
#include "fuaran.h"
